# Generated by Django 2.1.5 on 2019-07-09 11:21

from django.db import migrations
import django.contrib.gis.db.models.fields

class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
    	migrations.RunSQL(
            "ALTER TABLE api_climb ALTER COLUMN path TYPE geometry(LineStringZ,4326)",
        ),
        migrations.RunSQL(
            "ALTER TABLE api_town ALTER COLUMN location TYPE geometry(PointZ,4326)",
        ),
        migrations.RunSQL(
            "ALTER TABLE api_climb ALTER COLUMN location TYPE geometry(PointZ,4326)",
        ),
        migrations.RunSQL(
            "ALTER TABLE api_climb ALTER COLUMN start TYPE geometry(PointZ,4326)",
        ),
        migrations.RunSQL(
            "ALTER TABLE api_climb ALTER COLUMN summit TYPE geometry(PointZ,4326)",
        ),
        migrations.AlterField(
            model_name='province',
            name='area',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326),
        ),
    ]
