# Generated by Django 2.1.5 on 2019-08-21 08:24

from django.db import migrations
from django.contrib.postgres.operations import UnaccentExtension

class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20190709_1121'),
    ]

    operations = [
    	UnaccentExtension()
    ]
