# Generated by Django 2.1.5 on 2019-11-26 14:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20190821_0824'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='town',
            name='province',
        ),
        migrations.AddField(
            model_name='climb',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Town',
        ),
    ]
