# Generated by Django 2.2.7 on 2020-01-21 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_user_refresh_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='reset_password_token',
            field=models.CharField(db_index=True, max_length=255, null=True, unique=True),
        ),
    ]
