# Generated by Django 2.2.7 on 2020-02-03 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20200203_1006'),
    ]

    operations = [

        migrations.AlterUniqueTogether(
            name='bookmark',
            unique_together={('user', 'climb')},
        ),
    ]
